name = "rdebrid-worker-deployed2"
main = "server/app.ts"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "build/client"

# Uncomment and configure for custom domain:
# [[routes]]
# pattern = "your-domain.com"
# custom_domain = true

# All secrets are set via wrangler secret put command:
# wrangler secret put USERNAME
# wrangler secret put PASSWORD  
# wrangler secret put DEBRID_TOKEN